### ISSUE TITLE
Example of usage

### ISSUE THREAD

**Issue by eron93br** [suyog44/GT511C1R_PYTHON#1]
Hello suyog44, could you explain us how this code works?

May I need other library to use this code?

thanks

**Comment by suyog44** [comment]
Code has been constructed suing standard datasheet. 

///////////////////////////////// Retrived from datasheet (AS IT IS) /////////////////////////////////////////////////////////
STX1 = 0x55
STX2 = 0xAA

CMD_OPEN = 0x01
CMD_CLOSE = 0x02
CMD_LED = 0x12
CMD_GET_ENROLL_COUNT = 0x20
CMD_ENROLL_START = 0x22
CMD_ENROLL_1 = 0x23
CMD_ENROLL_2 = 0x24
CMD_ENROLL_3 = 0x25
CMD_IS_FINGER_PRESSED = 0x26
CMD_DELETE_ALL = 0x41
CMD_IDENTIFY = 0x51
CMD_CAPTURE_FINGER = 0x60

ACK = 0x30
NACK = 0x31
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Thid method sends 12 bytes command to GT511C3 and receive acknowledgement from it

def sendCmd(cmd, param=0):
    package = chr(STX1)+chr(STX2)+struct.pack('<hih', 1, param, cmd) //Packing command as short int short format
    checksum = calcChecksum(package) // Calculate the checksum
    package += struct.pack('<h', checksum)   // Merge checksum with package
    sent = port.write(package)                         // Finally write to the module
    if(sent != len(package)):
        print "Error communicating"
        return -1
    recv = port.read(sent) // Receving ACK
    recvPkg = struct.unpack('cchihh', recv)    //char char short int short short format 
    if recvPkg[4] == NACK:
        print("error: %s" % recvPkg[3])
        return -2
    time.sleep(1)
    return recvPkg[3]                                       // Return received 

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
if __name__ == "__main__":
    try:
        if port is None:
            port = serial.Serial(
                "/dev/ttyUSB3",                             // Change port number whatever you have
                baudrate=9600,                           // GT511C3 module work fine with 115200 you can change it                         
                timeout=None)
